# Copyright (c) 2025 Joe Walter
# GNU General Public License v3.0

from os import *
import sys
import tempfile
import shutil

from sftp import RemotePath

def normcase(p, ssh_version=None):
	if isinstance(p, RemotePath):
		'''
		assert ssh_version
		if "Win" in ssh_version or "win" in ssh_version:
			return str(p).lower()
		else:
			return p
		'''
		# TODO for now, just use the more restrictive Windows way
		return str(p).lower()
	else:
		return path.normcase(p)

def copy(src, dst, follow_symlinks=True):
	if isinstance(src, RemotePath) and isinstance(dst, RemotePath):
		with tempfile.NamedTemporaryFile(mode='w+b', delete=True) as temp_file:
			src_connection = src.connection
			src = str(src)
			if follow_symlinks:
				src = src.connection.normalize(src)
			src_connection.get(src, temp_file)

			dst_connection = dst.connection
			dst = str(dst)
			dst_connection.put(temp_file, dst)

	elif isinstance(src, RemotePath):
		connection = src.connection
		src = str(src)
		if follow_symlinks:
			src = src.connection.normalize(src)
		connection.get(src, dst)

	elif isinstance(dst, RemotePath):
		connection = dst.connection
		dst = str(dst)
		if follow_symlinks:
			src = src.resolve()
		connection.put(src, dst)

	else:
		shutil.copy2(src, dst, follow_symlinks=follow_symlinks)

class RemotePathScanner:
	def __init__(self, path):
		# path should always be followed if it is a symlink
		connection = path.connection
		#true_path = connection.normalize(path) # TODO not sure if this is needed
		self.entries = connection.listdir(str(path))
		self.index = 0

	def __iter__(self):
		return self

	def __next__(self):
		if self.index >= len(self.entries):
			raise StopIterationon
		item = self.entries[self.index]
		self.index += 1
		return item

	def __enter__(self):
		return self

	def __exit__(self):
		pass

def scan_path(p):
	if isinstance(p, RemotePath):
		return RemotePathScanner(p)
	else:
		return scandir(p)

# Copied from https://github.com/python/cpython/blob/main/Lib/os.py
# Modified lines are marked with ##################

# Private sentinel that makes walk() classify all symlinks and junctions as
# regular files.
_walk_symlinks_as_files = object()

def walk_path(top, topdown=True, onerror=None, followlinks=False):
	"""Directory tree generator.

	For each directory in the directory tree rooted at top (including top
	itself, but excluding '.' and '..'), yields a 3-tuple

		dirpath, dirnames, filenames

	dirpath is a string, the path to the directory.  dirnames is a list of
	the names of the subdirectories in dirpath (including symlinks to directories,
	and excluding '.' and '..').
	filenames is a list of the names of the non-directory files in dirpath.
	Note that the names in the lists are just names, with no path components.
	To get a full path (which begins with top) to a file or directory in
	dirpath, do path.join(dirpath, name).

	If optional arg 'topdown' is true or not specified, the triple for a
	directory is generated before the triples for any of its subdirectories
	(directories are generated top down).  If topdown is false, the triple
	for a directory is generated after the triples for all of its
	subdirectories (directories are generated bottom up).

	When topdown is true, the caller can modify the dirnames list in-place
	(e.g., via del or slice assignment), and walk will only recurse into the
	subdirectories whose names remain in dirnames; this can be used to prune the
	search, or to impose a specific order of visiting.  Modifying dirnames when
	topdown is false has no effect on the behavior of os.walk(), since the
	directories in dirnames have already been generated by the time dirnames
	itself is generated. No matter the value of topdown, the list of
	subdirectories is retrieved before the tuples for the directory and its
	subdirectories are generated.

	By default errors from the os.scandir() call are ignored.  If
	optional arg 'onerror' is specified, it should be a function; it
	will be called with one argument, an OSError instance.  It can
	report the error to continue with the walk, or raise the exception
	to abort the walk.  Note that the filename is available as the
	filename attribute of the exception object.

	By default, os.walk does not follow symbolic links to subdirectories on
	systems that support them.  In order to get this functionality, set the
	optional argument 'followlinks' to true.

	Caution:  if you pass a relative pathname for top, don't change the
	current working directory between resumptions of walk.  walk never
	changes the current directory, and assumes that the client doesn't
	either.

	Example:

	import os
	from path import join, getsize
	for root, dirs, files in os.walk('python/Lib/xml'):
		print(root, "consumes ")
		print(sum(getsize(join(root, name)) for name in files), end=" ")
		print("bytes in", len(files), "non-directory files")
		if '__pycache__' in dirs:
			dirs.remove('__pycache__')  # don't visit __pycache__ directories

	"""
	sys.audit("os.walk", top, topdown, onerror, followlinks)

	stack = [fspath(top)]
	islink, join = path.islink, path.join
	while stack:
		top = stack.pop()
		if isinstance(top, tuple):
			yield top
			continue

		dirs = []
		nondirs = []
		walk_dirs = []

		# We may not have read permission for top, in which case we can't
		# get a list of the files the directory contains.
		# We suppress the exception here, rather than blow up for a
		# minor reason when (say) a thousand readable directories are still
		# left to visit.
		try:
			with scan_path(top) as entries: ################## scandir -> scan_path
				for entry in entries:
					try:
						if followlinks is _walk_symlinks_as_files:
							is_dir = entry.is_dir(follow_symlinks=False) and not entry.is_junction()
						else:
							is_dir = entry.is_dir()
					except OSError:
						# If is_dir() raises an OSError, consider the entry not to
						# be a directory, same behaviour as path.isdir().
						is_dir = False

					if is_dir:
						dirs.append(entry.name)
					else:
						nondirs.append(entry) ################## entry.name -> entry

					if not topdown and is_dir:
						# Bottom-up: traverse into sub-directory, but exclude
						# symlinks to directories if followlinks is False
						if followlinks:
							walk_into = True
						else:
							try:
								is_symlink = entry.is_symlink()
							except OSError:
								# If is_symlink() raises an OSError, consider the
								# entry not to be a symbolic link, same behaviour
								# as path.islink().
								is_symlink = False
							walk_into = not is_symlink

						if walk_into:
							walk_dirs.append(entry.path)
		except OSError as error:
			if onerror is not None:
				onerror(error)
			continue

		if topdown:
			# Yield before sub-directory traversal if going top down
			yield top, dirs, nondirs
			# Traverse into sub-directories
			for dirname in reversed(dirs):
				new_path = join(top, dirname)
				# bpo-23605: path.islink() is used instead of caching
				# entry.is_symlink() result during the loop on os.scandir() because
				# the caller can replace the directory entry during the "yield"
				# above.
				if followlinks or not islink(new_path):
					stack.append(new_path)
		else:
			# Yield after sub-directory traversal if going bottom up
			stack.append((top, dirs, nondirs))
			# Traverse into sub-directories
			for new_path in reversed(walk_dirs):
				stack.append(new_path)
