# Copyright (c) 2025 Joe Walter
# GNU General Public License v3.0

import os
import unittest
import logging

from psync import core, filter, helpers, sftp, watch

logger = logging.getLogger("psync.tests")

class TestFilter(unittest.TestCase):

	def test_filter(self):
		f = filter.PathFilter(r"+ **")
		self.assertTrue(f.filter(None, "a"))
		self.assertTrue(f.filter(None, "a/b"))
		self.assertTrue(f.filter(None, "a/b/c"))
		self.assertTrue(f.filter(None, ".git/"))
		self.assertTrue(f.filter(None, "a/.git/"))
		self.assertTrue(f.filter(None, "a/b/.git/"))
		self.assertTrue(f.filter(None, "__pycache__/"))
		self.assertTrue(f.filter(None, "a/__pycache__/"))
		self.assertTrue(f.filter(None, "a/b/__pycache__/"))

		f = filter.PathFilter(r"+ **/*")
		self.assertTrue(f.filter(None, "a"))
		self.assertTrue(f.filter(None, "a/b"))
		self.assertTrue(f.filter(None, "a/b/c"))
		self.assertTrue(f.filter(None, ".git/"))
		self.assertTrue(f.filter(None, "a/.git/"))
		self.assertTrue(f.filter(None, "a/b/.git/"))
		self.assertTrue(f.filter(None, "__pycache__/"))
		self.assertTrue(f.filter(None, "a/__pycache__/"))
		self.assertTrue(f.filter(None, "a/b/__pycache__/"))

		f = filter.PathFilter(r"- **/.*/ **/__pycache__/ + **/*/ **/*")
		self.assertTrue(f.filter(None, "a"))
		self.assertTrue(f.filter(None, "a/b"))
		self.assertTrue(f.filter(None, "a/b/c"))
		self.assertFalse(f.filter(None, ".git/"))
		self.assertFalse(f.filter(None, "a/.git/"))
		self.assertFalse(f.filter(None, "a/b/.git/"))
		self.assertFalse(f.filter(None, "__pycache__/"))
		self.assertFalse(f.filter(None, "a/__pycache__/"))
		self.assertFalse(f.filter(None, "a/b/__pycache__/"))

		f = filter.PathFilter(r"+ audio/music/**/*.flac - **/*/ **/*")
		self.assertTrue(f.filter(None, "audio/"))
		self.assertTrue(f.filter(None, "audio/music/"))
		self.assertTrue(f.filter(None, "audio/music/OST/"))
		self.assertTrue(f.filter(None, "audio/music/OST/Star Wars/"))
		self.assertTrue(f.filter(None, "audio/music/OST/Star Wars/Duel of the Fates.flac"))
		self.assertFalse(f.filter(None, "video/"))
		self.assertFalse(f.filter(None, "audio/audiobooks/"))
		self.assertFalse(f.filter(None, "audio/music/OST/Star Wars/cover.jpg"))

		f = filter.PathFilter(r"- audio/music/**/*.wav + audio/music/**")
		self.assertTrue(f.filter(None, "audio/"))
		self.assertTrue(f.filter(None, "audio/music/"))
		self.assertTrue(f.filter(None, "audio/music/OST/"))
		self.assertTrue(f.filter(None, "audio/music/OST/Titanic/"))
		self.assertTrue(f.filter(None, "audio/music/OST/Titanic/cover.jpg"))
		self.assertFalse(f.filter(None, "audio/music/OST/Titanic/My Heart Will Go On (Recorder Cover).wav"))
		self.assertFalse(f.filter(None, "video/"))
		self.assertFalse(f.filter(None, "audio/audiobooks/"))

		f = filter.PathFilter(r"places.sqlite key4.db logins.json cookies.sqlite prefs.js")
		self.assertTrue(f.filter(None, "places.sqlite"))
		self.assertTrue(f.filter(None, "key4.db"))
		self.assertTrue(f.filter(None, "logins.json"))
		self.assertTrue(f.filter(None, "cookies.sqlite"))
		self.assertTrue(f.filter(None, "prefs.js"))
		self.assertFalse(f.filter(None, "storage.sqlite"))
		self.assertFalse(f.filter(None, "storage/"))

		f = filter.PathFilter("'**/a b' \"**/A B\" **/'x y'  Joe\\'s\\ File")
		self.assertTrue(f.filter(None, "**/a b"))
		self.assertFalse(f.filter(None, "a b"))
		self.assertFalse(f.filter(None, "1/2/a b"))
		self.assertTrue(f.filter(None, "A B"))
		self.assertTrue(f.filter(None, "1/2/A B"))
		self.assertTrue(f.filter(None, "x y"))
		self.assertTrue(f.filter(None, "1/2/x y"))
		self.assertTrue(f.filter(None, "Joe's File"))
		self.assertFalse(f.filter(None, "a"))

		f = filter.PathFilter("\"'a'\"   '\"b\"'   \"x ?\"'y ?' ")
		self.assertTrue(f.filter(None, "'a'"))
		self.assertTrue(f.filter(None, "\"b\""))
		self.assertTrue(f.filter(None, "x 1y ?"))
		self.assertFalse(f.filter(None, "x 1y 2"))

		f = filter.PathFilter(r"+ * - a/ b/a/ + b/*/ - **/x + ?/**/* - **/*")
		self.assertTrue(f.filter(None, "a"))
		self.assertTrue(f.filter(None, "b/a"))
		self.assertTrue(f.filter(None, "b/a/a"))
		self.assertTrue(f.filter(None, "b/b/"))
		self.assertFalse(f.filter(None, "a/"))
		self.assertFalse(f.filter(None, "b/a/"))
		self.assertFalse(f.filter(None, "b/b/x"))
		self.assertTrue(f.filter(None, "b/y"))
		self.assertTrue(f.filter(None, "b/b/y"))
		self.assertFalse(f.filter(None, "aa/y"))

		f = filter.PathFilter(r"+ a B - A b c + **/*", ignore_hidden=True, ignore_case=True)
		self.assertTrue(f.filter(None, "a"))
		self.assertTrue(f.filter(None, "A"))
		self.assertTrue(f.filter(None, "b"))
		self.assertTrue(f.filter(None, "B"))
		self.assertFalse(f.filter(None, "c"))
		self.assertFalse(f.filter(None, "C"))
		self.assertFalse(f.filter(None, ".a"))
		self.assertFalse(f.filter(None, ".A"))
		self.assertFalse(f.filter(None, "d/.a"))
		self.assertFalse(f.filter(None, "d/.A"))

		f = filter.PathFilter(r"./a/ ./a/b")
		self.assertTrue(f.filter(None, "a/"))
		self.assertTrue(f.filter(None, "a/b"))
		self.assertFalse(f.filter(None, "c"))

		f = filter.PathFilter(r"a/ a/b")
		if os.sep == "\\":
			self.assertTrue(f.filter(None, "a/"))
			self.assertTrue(f.filter(None, "a\\"))
			self.assertTrue(f.filter(None, "a/b"))
			self.assertTrue(f.filter(None, "a\\b"))
			self.assertFalse(f.filter(None, "c"))
		else:
			self.assertTrue(f.filter(None, "a/"))
			self.assertFalse(f.filter(None, "a\\"))
			self.assertTrue(f.filter(None, "a/b"))
			self.assertFalse(f.filter(None, "a\\b"))
			self.assertFalse(f.filter(None, "c"))

		f = filter.PathFilter(r"a\\ a\b")
		if os.sep == "\\":
			self.assertTrue(f.filter(None, "a/"))
			self.assertTrue(f.filter(None, "a\\"))
			self.assertTrue(f.filter(None, "a/b"))
			self.assertTrue(f.filter(None, "a\\b"))
			self.assertFalse(f.filter(None, "c"))
		else:
			self.assertFalse(f.filter(None, "a/"))
			self.assertTrue(f.filter(None, "a\\"))
			self.assertFalse(f.filter(None, "a/b"))
			self.assertTrue(f.filter(None, "a\\b"))
			self.assertFalse(f.filter(None, "c"))

		f = filter.PathFilter(r"'- a' -a -- a\  a\ - ./- \"a a\'b")
		self.assertTrue(f.filter(None, "- a"))
		self.assertTrue(f.filter(None, "-a"))
		self.assertTrue(f.filter(None, "--"))
		self.assertTrue(f.filter(None, "a "))
		self.assertTrue(f.filter(None, "a -"))
		self.assertTrue(f.filter(None, "-"))
		self.assertTrue(f.filter(None, "\"a"))
		self.assertTrue(f.filter(None, "a'b"))
		self.assertFalse(f.filter(None, "b"))

		f = filter.PathFilter(r"'-'")
		self.assertTrue(f.filter(None, "-"))
		self.assertFalse(f.filter(None, "a"))

		f = filter.PathFilter("\"-\"")
		self.assertTrue(f.filter(None, "-"))
		self.assertFalse(f.filter(None, "a"))

		self.assertRaises(ValueError, filter.PathFilter, r"+ \-")
		self.assertRaises(ValueError, filter.PathFilter, r"+ 'a")
		self.assertRaises(ValueError, filter.PathFilter,  "+ a\\")
		self.assertRaises(ValueError, filter.PathFilter,  "+ /a")

		if os.sep == "\\":
			self.assertRaises(ValueError, filter.PathFilter,  "+ \\/a")
			self.assertRaises(ValueError, filter.PathFilter,  "+ \\\\a")

		f = filter.PathFilter("a/ b/ ./1 c/ c/d/ ./2")
		self.assertFalse(f.filter(None, "1"))
		self.assertTrue(f.filter(None, "a/1"))
		self.assertTrue(f.filter(None, "b/1"))
		self.assertTrue(f.filter(None, "a/2"))
		self.assertTrue(f.filter(None, "b/2"))
		self.assertFalse(f.filter(None, "c/1"))
		self.assertTrue(f.filter(None, "a/2"))
		self.assertTrue(f.filter(None, "b/2"))
		self.assertTrue(f.filter(None, "c/2"))
		self.assertFalse(f.filter(None, "c/3"))
		self.assertTrue(f.filter(None, "c/d/2"))
		self.assertFalse(f.filter(None, "d/2"))

		f = filter.PathFilter("a/ - b/ + c/ d ./1 + e/ ./**/*")
		self.assertFalse(f.filter(None, "a/1"))
		self.assertFalse(f.filter(None, "b/1"))
		self.assertTrue(f.filter(None, "c/1"))
		self.assertFalse(f.filter(None, "d/1"))
		self.assertTrue(f.filter(None, "e/e/e/1"))

		f = filter.PathFilter("a/b/ ./1")
		self.assertFalse(f.filter(None, "a/1"))
		self.assertFalse(f.filter(None, "b/1"))
		self.assertTrue(f.filter(None, "a/b/1"))
